name: Pipeline

#events
on:
  push:
    branches: [ "cicdtest" ]
    #when someone pushes to branch main it triggers this workflow
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4 #predefined action from the marketplace

    - name: Set up JDK 17 & Maven
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Check files
      run: ls -la

    - name: Start MySQL
      run: |
        docker ps
        #docker compose down
        echo 'Starting MySQL with Docker Compose...'
        docker compose up mysql -d
        echo "Waiting for MySQL to be ready..."
        until [ "`docker inspect -f {{.State.Health.Status}} mysql_db`" == "healthy" ]; do
          sleep 5;
        done

    - name: Check running containers
      run: docker ps

    - name: Check MySQL logs
      run: docker logs mysql_db

        # - name: Test MySQL Connection
        #run: |
        #echo 'Testing MySQL connection...'
        #docker exec mysql_db mysqladmin ping -h mysql_db

    - name: Build
      run: |
        echo 'Clean and package the application'
        mvn clean package -Dspring.datasource.url=jdbc:mysql://localhost/petclinic

    - name: Test
      run: mvn test

    - name: Deploy
      run: |
        echo 'Starting App with Docker Compose...'
        docker compose up --build -d
        echo 'Waiting for the application to start...'
        sleep 10

    - name: Check containers
      run: docker ps
